gjs: Autospec creation for update from version 1.72.0 to version 1.72.1
Evan Miller (2):
      value: Fix compilation error on Darwin
      profiler: Align types in function definition with header file

Marco Trevisan (Treviño) (5):
      test-ci: Ignore safe directory errors on CI
      arg-cache: Do not leak an interface info structures on Callbacks
      arg-cache: Make explicit when BaseInfo is adding a reference
      arg-cache: Mark few more constructors as constexpr
      jsapi-util-strings: Ignore locale to compute the upper case of a char

Philip Chimento (3):
      build: Post-release version bump
      Fix codespell
      release: Prepare for 1.72.1

msizanoen1 (1):
      arg-cache: Use BoxedInTransferNone::release for GBytesInTransferNone::release

Version 1.72.1
--------------

- Various fixes ported from the development branch.

- Closed bugs and merge requests:
  * Compilation error: call to deleted function 'js_value_to_c' [#473, !738,
    Evan Miller]
  * jsapi-util-strings: Ignore locale to compute the upper case of a char (i.e.
    fix implicit properties on Turkish locale) [!742, Marco Trevisan]
  * Fix memory leak when passing a "transfer none" GBytes parameter to a native
    function [!746, msizanoen1]
  * arg-cache: Do not leak an interface info structures on Callbacks [!751,
    Marco Trevisan]
  * test-ci: Ignore safe directory errors on CI [!755, Marco Trevisan]