gjs: Autospec creation for update from version 1.58.4 to version 1.64.2
Andy Holmes (5):
      docs: Update internal links
      Gtk Templates: support connectObj argument
      Gio override: optimize constructor param checks in _init
      Gio override: check for missing or conflicting schema path
      examples: add a dbus-client and dbus-service example

Bastien Nocera (1):
      build: Fix installation with DESTDIR set

Chun-wei Fan (17):
      meson.build: Symlink gjs to gjs-console in a Python script
      meson: Convert build/compile-gschemas.sh into Python
      gjs/context.cpp: Make typelib search path consistent
      meson.build: Don't check for GCC-specific items on MSVC
      gjs/*.cpp, util/*.cpp: Check for sys/signal.h and _WIN32
      meson.build: Fix introspection builds on MSVC
      test/meson.build: Do not build on Windows
      installed-tests/meson.build: Skip simple tests for MSVC builds
      win32/README.txt: Move to $(srcroot)/README.MSVC.md
      meson.build: Look for Cairo manually on MSVC builds
      meson.build: Don't run build/choose-tests-locale.sh
      installed-tests/js/meson.build: Fix building test DLLs
      README.MSVC.md: Update build documentation
      installed-tests/js/meson.build: Don't use -Wno-error on MSVC
      gi/arg.cpp, gjs/importer.cpp: Avoid C++ ambiguity
      gjs/global.cpp: Fix linking on Visual Studio builds
      README.MSVC.md: Update build instructions

Colin Walters (1):
      object: Use g_irepository_get_object_gtype_interfaces

Evan Welsh (2):
      modules: Reorganize modules to support multiple globals.
      Check if STRV value is an object before toObject.

Florian Müllner (8):
      GObject: Add convenience wrapper for signal_handler_(un)block()
      util: Don't free memory we do not own
      CI: Tweak eslint rule for unneeded parentheses
      build: Fix dist files
      GObject: Add convenience wrapper for signal_stop_emission_by_name()
      object: Warn when setting a deprecated property
      overrides/Gtk: Fix template support with Gtk4
      installed-tests: Test both GTK3 and GTK4

Giovanni Campagna (1):
      boxed: mark structs with gpointer fields as simple

Jan Alexander Steffens (heftig) (3):
      installed-tests/js: Add missing dep on warnlib_typelib
      build: Add -fno-semantic-interposition to -Bsymbolic-functions
      object: Fix dangling pointer crash

Jan Tojnar (5):
      vuild: Pass schemadir to compile-gschemas.py
      build: Use more traditional installed-tests variables
      build: Make installed tests vars absolute
      build: Use installed_tests_execdir in the .test files
      build: Install test libraries under installed_tests_execdir

Juan Pablo Ugarte (3):
      jsapi-util: add GjsAutoFree
      object: fix property regression
      Add test for no introspection data.

Liban Parker (1):
      Fix failed redirect of output in CommandLine tests

Marco Trevisan (Treviño) (17):
      private: Don't pass argv to for_js_typecheck and use result for later
      testGObjectClass: Verify the usage of GObject classes with wrong base
      GObject: Optionally use the caller script basename to define the GType
      testGObject: Verify that GType name is computed for registered classes
      GObject: Sanitize provided GTypeName to match allowed ones
      testGObjectClass: Verify that we properly sanitize the provided GType name
      gjs: Ensure that GjsContextPrivate::from_current_context is not inlined
      jsapi-util-root: Add JSContext parameter to switch_to_unrooted
      object: Use GjsContextPrivate::from_current_context() to get context
      test-coverage: Ignore format-nonliteral warning
      context: Move gjs_get_import_global to jsapi-util
      meson, autotools: Hide non-exported symbols by default
      function: Pass the deferenced callback out pointer value to JS
      testGIMarshalling: Verify vfunc inout parameters are correctly hanled
      testGIMarshalling: Don't try to override methods we may not have
      testRegress: Always enable tests depending on old MR
      function: Don't crash if a callback doesn't return an array of values

Michael Catanzaro (1):
      Revert "build: Remove Autotools build system"

Niels De Graef (1):
      Don't pass generic marshaller to g_signal_newv()

Philip Chimento (152):
      GLib: Override string manipulation functions
      build: Post-branch version bump
      CI: Create cpplint image using Alpine Linux
      CI: Use "mozjs" consistently
      CI: Consolidate image build scripts in test/ci-images.sh
      CI: Don't run examples/webkit.js
      CI: Clean up packages installed on the Docker image
      CI: Install mozjs in /usr/local on Docker images
      CI: Remove BUILD_MOZ command from Docker image script
      GObject: Fix linter error
      CI: Reinstate "NAME" variable
      CI: Remove check for IMAGE variable
      CI: Put docker command on one line
      CI: Quote variables consistently in bash scripts
      CI: Use new Docker images
      CI: Add dbus-x11 to CI images
      object: Throw if constructing an unregistered object inheriting from GObject
      CI: Update pinned job
      CI: Add diffutils to Docker image
      CI: Generate machine ID on Docker image
      tests: Fail debugger tests if command failed
      build: Meson build system
      build: Port IWYU runner script to use compilation database
      build: Port cppcheck target to use compilation database
      CI: Add meson CI job
      docs: Update Hacking.md to use Meson workflow
      build: Bump gobject-introspection requirement to 1.61.2
      release: Copy NEWS from 1.58.1
      release: Prepare for 1.63.1
      build: Post-release version bump
      CI: Remove header / footer
      CI: Remove CODECHECK variable
      CI: Use Meson-based script for code coverage jobs
      CI: Remove do_Get_Commit_Message
      CI: Add test-ci.sh SETUP command
      build: Fix regress.c args
      CI: Move most CI jobs to Meson
      build: Adjust test timeouts
      build: Install files needed for debugger tests
      build: Install libwarnlib.so
      test: Accommodate GC zeal parameters in test skip condition
      test: Remove pending timeout source after test
      build: Correctly report version in code coverage report
      build: Run tests one at a time when collecting coverage
      build: Handle case where $bindir/gjs symlink already exists
      build: Run coverage jobs in XVFB
      jsapi-dynamic-class: Switch to RAII classes
      build: Fix unused variable warnings
      object: Add clarifying comment
      object: Update bug link in comment
      console: Exit more gracefully when unknown command line option given
      arg: Use HandleValue in gjs_array_to_array()
      function: Improve error messages
      object: Handle error from gjs_callback_trampoline_new()
      object: Move argument checking out of props_to_g_parameters()
      tests: Add more Regress tests
      arg: Avoid data corruption when marshalling unsupported flat array
      arg: Support flat arrays of structs
      cairo: Add type checking to Path, Pattern, and Surface
      object: Warn if passing more than one argument to default constructor
      function: Don't always js::DumpStack() in blocked callbacks
      GObject: Check implementing Gio.AsyncInitable
      release: PRepare for 1.63.2
      build: Post-release version bump
      build: Mark SweepingAPI.h as a system header
      CI: Treat warnings as errors
      tests: Test for empty flat arrays of structs
      build: Remove Autotools build system
      profiler: Change message to not depend on build system
      Revert "Revert "build: Remove Autotools build system""
      build: Make LSan exit with code 23 on leaks
      build: Suppress LSan on System.exit() test
      build: Quiet output of invalid option test
      build: Rewrap meson error messages
      CI: Fix arguments to diff command
      lint: Preserve include blocks with clang-format
      build: Improve IWYU script
      build: Add global slot constants to IWYU mapping file
      lint: Make header include changes suggested by IWYU
      mem: Add GJS_FOR_EACH_COUNTER
      cairo: Remove unused fields from private structures
      build: Remove unused import from python script
      jsapi-util-string: Make debug print functions handle null
      function: Improve debug message
      js: Remove most goto error handling
      build: Don't error out on warnings in test GIR sources
      profiler: Call destructor of PseudoStack
      CI: Create mozjs68 CI images
      doap: Update bug database link
      doap: Use SPDX entity links for software licenses
      doap: Update homepage
      global: Define debug names for compartments
      build: Add -Wno-typedef-redefinition to C compiler arguments
      console: Remove trailing newline from log message
      release: Add NEWS from 1.58.4
      release: Prepare for 1.63.3
      build: Post-release version bump
      build: Prefer signal.h to sys/signal.h
      build: Change CI to run on mozjs68 images
      build: Build with mozjs68
      js: Remove requests
      js: Rename "compartments" to "realms"
      js: Rename JS::AutoFooVector
      js: Various API renames
      js: Remove hashtable init() calls
      js: Use new warnings API
      js: Remove handling of shebang line
      js: Use JS::SourceText to store source code
      js: Change gjs_string_to_utf8() to return JS::UniqueChars
      gerror: Pass null JSPrincipals to saved frame API calls
      object: Use "associated memory" API instead of malloc counter
      byteArray: Use new ArrayBuffer API
      global: Use default global ClassOps
      engine: Remove locale callbacks
      engine: Add missing headers
      context: Rewrite promise job queue
      jsapi-util-string: Remove no-copy optimization in gjs_string_from_ucs4()
      tests: Minor changes in debugger and coverage expected output
      docs: Update documentation for SpiderMonkey 68
      js: Remove jsapi-wrapper.h
      tests: Add weak pointer callback in tests with untraced weak pointer
      gtype: Don't use lookupForAdd() when adding GType to table
      object: Add overrides for signal matching methods
      docs: Fix badge in README
      build: Remove duplicate meson argument
      release: Prepare for 1.63.90
      build: Post-release version bump
      maint: Run eslint job when eslint config files change
      maint: Fix eslint errors
      doc: Update references to module files in documentation
      object: Bypass read barrier in jsobj_addr()
      wrapper: Change type of debug addresses to void*
      object: Cache known unresolvable properties
      release: Prepare for 1.63.91
      tests: Avoid filename conflict when tests run in parallel
      maint: Make all operator bool explicit
      build: Late post-release version bump
      release: Prepare for 1.63.92
      build: Post-release version bump
      release: Prepare for 1.64.0
      build: Post-release version bump
      build: Remove last traces of Autotools
      build: Handle missing /usr/bin/locale
      linter: Bump JS version to ES2019
      global: Enable BigInt
      release: Prepare for 1.64.1
      build: Post-release version bump
      arg: Factor out determination of GITypeInfo storage type
      arg: Fix GList and GHashTable marshalling on 64-bit big-endian
      jsapi-util: Fix gjs_log_exception() for InternalError
      object: Fix signal match mechanism
      release: Prepare for 1.64.2

Ross Burton (1):
      installed-tests: skip some tests if GTK can't be initialised

Simon McVittie (2):
      arg: Fix GHashTable key marshalling on 64-bit big-endian
      function: Use GIArgument.v_int for enum and flags types

Sonny Piers (2):
      add http client example
      add websocket client example

Ting-Wei Lan (1):
      installed-tests: Don't hardcode the path of bash

Xavier Claessens (1):
      Respect transfer/allow-none annotation on return/out args of a callback/vfunc

Version 1.64.2
--------------

- Closed bugs and merge requests:
  * GList of int not correctly demarshalled on 64-bit big-endian [Philip
    Chimento, Simon McVittie, #309, !417, !419]
  * Fix template use in GTK4 [Florian Müllner, !420]
  * Don't crash if a callback doesn't return an expected array of values [Marco
    Trevisan, !405]
  * Crash passing integer to strv in constructor [Evan Welsh, #315, !422]
  * Skip some tests if GTK can't be initialised [Ross Burton, !421]

- Various backports:
  * Fix gjs_log_exception() for InternalError [Philip Chimento]
  * Fix signal match mechanism [Philip Chimento]

(NEWS truncated at 15 lines)