gjs: Autospec creation for update from version 1.68.3 to version 1.70.0
Andy Holmes (3):
      doc: Add simple sysprof example
      examples: add examples of GtkBuilder templates
      GDBus Implementation: fix invalidating properties when emitting changes

Carlos Garnacho (3):
      GObject: Ensure to call setter methods for construct-only properties
      GObject: Call only setter for JS-defined construct-only properties
      object: Avoid setting construct properties multiple times

Chun-wei Fan (8):
      meson.build: Ignore warning C5030 on Visual Studio
      installed-tests: Fix building libgjstesttools
      build: Define WIN32_LEAN_AND_MEAN on Windows builds
      gjs/text-encoding.cpp: Replace strcasecmp with g_ascii_strcasecmp
      gjs_pch.hh: Include alloca.h and syscall.h in profiler builds
      build: Fix PCH on Visual Studio
      README.MSVC.md: One more fix in the SpiderMonkey headers
      text-encoding.cpp: Fix builds on 64-bit Windows

Daniel van Vugt (2):
      meson.build: Avoid putting two copies of libsysprof-capture-4.a in libgjs
      cairo-surface: Add setDevice{Offset,Scale} functions

Evan Welsh (38):
      gi: Correctly hold references for gvariant transfer parameters
      byteArray: Refactor functionality into Encoding
      ByteArray: Add jsdoc to ByteArray.fromArray()
      ByteArray: Clarify eslint override
      jsapi-util-string: Clean up gjs_string_from_utf8() to use early return
      text-encoding: Factor out UTF-16 codeset into a string constant
      text-encoding: Improve and factor out check for "UTF-8" encoding
      modules: Add helper to load context setup modules
      modules: Add bootstrap file with ESM support
      gi: Only enumerate properties which GJS defines
      Ensure the correct realm is entered in the async executor
      Fix race condition in dynamic module resolution.
      Add test for dynamic import resolution
      object: Enqueue toggle ups when the heap is collecting
      ByteArray: Implement ByteArray.toGBytes() in JS
      win32: Fix resource-based imports
      modules: Support zero-terminated and fixed length encoding.
      modules: Implement fatal TextEncoder and TextDecoder APIs
      modules: Implement non-fatal encoding and decoding
      modules: Add tests for Encoding
      overrides: Implement overrides for structured logging hook
      ci: Increase default timeout for additional tests
      modules: Cleanup JSDoc, use ArrayBuffer.isView(), and use Object.defineProperty
      Set quote_type in editorconfig
      modules: Implement WHATWG console specification
      util: Add console handling utility
      modules: Implement console.clear()
      Update ESLint to v8
      gi: Don't zero terminate strings passed for bytes
      gi: Return null if return argument is a pointer type
      gi: Convert GJS values to 64-bit GValue integers
      esm: Guard debugging log which assumes importing privates are objects
      gi: Enable pending tests which are now correctly handled
      gi: Assume native enums are signed, avoid asserting.
      Use g_assert_true in test tools
      Increase sanitizer timeout multiplier
      Fix IWYU CI job.
      Ensure instance constructor values are chained from Gtk.Widget

Florian Müllner (7):
      ns: Expose __version__ property
      esm/gi: Use __version__ property to check for conflicts
      modules/internalLoader: Drop version map/check
      arg-cache: Handle notified callbacks without destroy
      overrides/GLib: Guard Error.new_literal against invalid domains
      Add override for g_object_bind_property_full()
      debugger: Add option to ignore caught exceptions

Jordan Petridis (1):
      meson: fix version check for precompiled headers

Marco Trevisan (Treviño) (93):
      wrapperutils: Use native ostringstream pointer to string conversion
      fundamental: Improve error message about invalid conversion types
      testFundamental: Add more tests ensuring we can upcast but not downcast
      fundamental: Use g_value_type_compatible to check if we can do type conversion
      fundamental: Also allow to transform a fundamental to a compatible gvalue
      testGObjectValue: Add GValue conversion test for GObject objects
      testGObjectValue: Add tests ensuring we can create GValue's for boxed types
      testGObjectValue: Add cases with GValue holding a GValue
      value: Support creating a GType from a GValue holding it
      testGObjectValue: Check that GValue's can be passed to functions
      testGIMarshalling: Add pending test for object string property
      arg: Dynamically get the gtype from JS object when none is provided
      fundamental: Support converting an empty GValue to a null fundamental
      testGObjectValue: Add tests setting an instance using a fundamental type
      object: Pass the instance pointer to toggle notify
      object: Switch back to normal references on disposal
      object: Use the term "DISPOSED" for objects in such state, not FINALIZED
      object: Catch finalized objects that are still under gjs scope
      object: Discard disposed GObject's and do not create wrappers for them
      object: Also unset the object qdata during wrapper destruction
      testGtk3: Ensure that disposed signal callback gets called with valid object
      testGobjectDestructionAccess: Verify usage of vfunc_dispose
      object: Never try to add a toggle reference on a disposed object
      installed-tests: Add GjsTestTools utilities to call native code for evil ops
      testGObjectDestructionAccess: Verify that disposed object is monitored
      object: Discard wrapper when GObject is disposed from main thread
      object: Cancel queued toggles on dispose notify
      object: Safely handle disposal when happening from other thread
      object: Do not disassociate a JS object if we have queued toggle up
      toggle: Initialize private variables on construction
      toggle: Add utility function to handle all toggles
      GjsTestTools: Move open_bytes here from GjsPrivate
      object: Improve debugging during wrapping/unwrapping GObject
      gjs-test-tools: Use `g_prefix_error` instead of using that ourself
      testGObjectDestructionAccess: Ensure that disposed wrappers are unbound
      object: Block access to object only if it is finalized
      gjs-test-tools: Ensure we use thread safe access to the saved object
      gjs-test-tools: Return GThread's when we don't join immediately
      arg-cache: Do not mark a function returning void* as skip-all
      testGObjectDestructionAccess: Check toggle events after the wrapper destruction
      toggle: Rely on wrapper to cancel finalized objects in queue
      toggle: Keep track of objects via ObjectInstance not GObject's
      toggle: Enforce thread-safety using a per-thread spin-lock
      object: Rely on next ToggleQueue iteration to handle already queued toggle events
      context: Ensure we check atomically if we're destroying from other threads
      log: Make logging thread safe
      log: Optimize topics check avoiding repeated strings checks
      repo: Always return on gjs_info_type_name to ensure it works without asserts
      installed-tests: Mark thread-safe tests using a suite and run them in CI
      gjs-test-tools: Adjust meson configuration, removing duplicated depends
      gjs-test-tools: Throw error if we can't create threads
      testGObjectDestructionAccess: Ignore errors when creating many threads
      gjs: Define once GCPolicy instead of repeating it all over the places
      function: Move Function into the Gjs namespace to be unique
      gjs: Ensure that we always use unique names for static values and types
      build: Add support to Unity builds and add a CI job testing it
      build: Support building with precompiled headers
      meson: Ignore precompiled headers option under g++ and earlier versions of meson
      test: Add a CI job that ensures that PCH file is populated with all headers
      ci: Only perform iwyu builds when actual sources or build parameters changed
      gjs_pch: Also include the mozjs required defines part of cflags
      test: Move assert_equal definition into Gjs::Test and common header
      tests: Move internal API tests into a different test binary
      tests: Add unit tests for ToggleQueue and ObjectInstance usage of it
      ci: Use unity build with the maximum size possible
      test: Move gjs-test code into Gjs::Test namespace
      jsapi-util: Add GjsAutoPointerSimple to avoid repeating the same type
      arg-inl: Use more auto-generated code avoiding typed parameters
      mem-private: Do not use volatile for atomic values
      context: Use native c++ thread to keep track of the context thread
      object: Move private callbacks to the private scope
      object: Optimize a bit AutoGValueVector usage
      jsapi-util-root: Mark some constexpr operations as such
      gjs-test-utils: Be more liberal in comparing values of different types
      context: Ensure that the GjsContext object is disposed from the owner thread
      context: Handle dispose notify manually
      object: Make ensure_toggle_reference to follow the JS API so we can throw
      Value: add Gjs::AutoGValue and use this to handle lifetime of GValues
      object: Use AutoGValueVector to build a list of GValue signal arguments
      utils: Add inline function to remove from unsorted vectors
      object: Invalidate closures while iterating, avoiding recursion
      gjs_pch: Only include sysprof-capture if profiler is enabled
      build: Use pch header for the internal library
      build: Disable glib assertions via G_DISABLE_ASSERT on release builds
      mem: Reimplement counters using c++ atomic and constexpr expressions
      object: Use vector for holding the list of wrapped objects
      context: Move garbage collection handling callback into context
      closure: Reimplement to be a C++ class with custom heap allocator
      GjsCallBackTrampoline: Inherit from Gjs::Closure (and so GClosure)
      function: Use minimal allocation for trampoline data
      GjsMaybeOwned: Remove notifier support and move it into GjsPrivateContext
      context: Cleanup completed trampoline in context, as this is what they belong to
      object: Use vector for holding the list of wrapped objects

Philip Chimento (71):
      arg-cache: Never throw when building the argument cache
      function: Save original allocated pointers
      maint: Mark functions as [[gnu::const]]
      maint: Replace G_GNUC_... macros with C++ attributes
      tests: Fix GIMarshallingTests.SubSubObject tests
      tests: Increase coverage of Regress and GIMarshalling test suite
      jsapi-util-string: Return smart pointer from gjs_hyphen_to_underscore()
      value: Rewrite incorrect and obsolete comments
      gerror: Make gjs_gerror_make_from_error() infallible
      system: Add missing functions to System module
      build: Add Flatpak manifest
      docs: Add note about building SpiderMonkey
      build: Post-branch version bump
      closure: Clean up gjs_closure_invoke()
      jsapi-util-string: Print quotes around strings in gjs_debug_value()
      jsapi-util-string: Placeholder debug string for BigInt
      gerror: Handle any value when converting thrown value to GError
      arg-cache: Fix rebase collision
      context: Don't prepend installed GjsPrivate search path if uninstalled
      heapgraph: Add special formatting for Proxy nodes
      context: Collect nursery before heap dump
      system: Use RAII in System.dumpHeap and logging for file pointer
      byteArray: Fix crash with 0-length GLib.Bytes
      byteArray: Fix crash with 0-length string
      jsapi-util-string: Handle BigInt in gjs_debug_value()
      maint: Add linter rule for multiline object literals
      CI: Correct task ID for TSAN job
      gettext: Export LocaleCategory enum in ES module
      CI: Add autoconf213 to dependencies in Dockerfile
      jsapi-util-args: Fix obsolete comments
      jsapi-util-args: Improve template for free_if_necessary
      jsapi-util-args: Fix assert_match() in tests
      jsapi-util-args: Add 'S' conversion specifier
      internal: Use gjs_parse_call_args() in internal module loader functions
      maint: Fix includes
      context: Improve profiling data for garbage collections
      mem: Add index to counter macros
      profiler: Define sysprof counters for the GObject wrapper counts
      system: Add System.dumpMemoryInfo() API
      maint: Fix lint errors
      Add Internship Getting Started documentation
      docs: Replace IRC and mailing list with Matrix and Discourse
      docs: Fix out of date details in docs
      docs: Add instructions for installing mozjs78 with package manager
      maint: Add links to IWYU bug numbers for false positives
      internal: Switch to compiling UTF-8 script directly
      maint: Use GLib UTF8-to-UTF16 functions
      maint: Use GjsAutoPointer out() method
      text-encoding: Clarify whitespace-stripped encoding
      build: Fix building with gobject-introspection as a subproject
      build: Provide fallback location for GLib Valgrind suppressions
      build: Remove bash-ism
      build: Accommodate iwyu_tool named iwyu_tool.py
      build: Fix IWYU errors
      release: Add NEWS from stable release 1.68.1
      release: Add NEWS from stable release 1.68.2
      release: Prepare for 1.69.1
      build: Post-release version bump
      CI: Codespell fixes
      cairo: Add Surface.getDeviceScale and Surface.getDeviceOffset
      release: Add NEWS from stable release 1.68.3
      release: Prepare for 1.69.2
      maint: Fix cppcheck warning about returning integer as pointer
      maint: Avoid bogus cppcheck warning about one-definition rule
      CI: Don't skip checks depending on what files were changed
      CI: Print versions of linters before each linter check
      maint: Fix trailing spaces
      function: Warn about unhandled promise rejections in System.exit()
      release: Prepare for 1.69.90
      release: Add NEWS from stable release 1.68.4
      release: Prepare for 1.70.0

Philip Withnall (1):
      subprojects: Use GLib main branch

Sonny Piers (4):
      doc: document shebang for ESModules
      doc: add Almond to applications
      doc: add Commit to applications
      examples: improve the gettext example

Veena Nagar (1):
      GObject properties with GByteArray type

dependabot[bot] (2):
      build(deps): bump lodash from 4.17.20 to 4.17.21 in /tools
      build(deps): bump glob-parent from 5.1.1 to 5.1.2 in /tools

veena (5):
      Add overrides for Gio.ListStore.insert_sorted and Gio.ListStore.sort
      modified _promisify function
      Revert "object: Use vector for holding the list of wrapped objects"
      modified _promisify function
      modified _promisify function

veenanitk (1):
      modified messsage

Version 1.70.0
--------------

- No changes from release candidate 1.69.90.

Version 1.68.4
--------------

- Build fix backported from the development branch. [#436, !667, Evan Welsh]

Version 1.69.90
---------------

- Closed bugs and merge requests:

(NEWS truncated at 15 lines)