[update to 1.58.0] Gtk: Provide better message when forgetting a template signal handler
Andy Holmes (1):
      Docs: add documentation for logging functions

Christian Hergert (6):
      console: fix dangling pointer
      profiler: avoid clearing 512 bytes of stack
      profiler: port to sysprof-capture-3
      profiler: record duration of GC sweeps
      profiler: add support for GJS_TRACE_FD
      profiler: auto-flush capture writer every 3 seconds

Florian Müllner (13):
      object: Throw when trying to instantiate an abstract type
      private: Allow passing type flags to register_type
      debugger: Fix summary help
      build: Bump glib requirement
      gobject: Use auto-compartment when getting property as well
      tests: Add test for child_set_property() with null values
      gi: Avoid infinite recursion when converting GValues
      gtk-util: Reformat
      gtk-util: Reimplement with introspection
      gjs-private: Move GTK override into util
      gjs-private: Work around a gobject-introspection bug
      build: Stop linking with GTK3
      Gtk: Make gtk_container_child_set_property() override optional

Jason Hicks (1):
      mainloop: Assign null to property instead of deleting

Jonas Dreßler (1):
      modules/signals: Use array destructuring in _emit

Marco Trevisan (Treviño) (21):
      gobject: Use auto-compartment on object when setting property
      system: add addressOfGObject method
      Gio: Make possible to pass DBusProxyFlags to proxy wrapper
      Gio: Fix makeProxyWrapper indentation
      wrapperutils: Remove double null check on to_string
      Gio: Use singlequote for strings
      Gio: Use more lambda funcs and binds
      Gio: Don't make properties on DBus proxy wrapper configurable
      testGDBus: Verify that properties are set/got to/from server
      testGDbus: Use a verbatim string for interface definition
      GjsMaybeOwned: remove void parameter on empty functions
      object: Pass std::function objects by reference
      Gio: Throws errors when trying to set/read readonly/writeonly properties
      GjsMaybeOwned: Don't use union for root and heap
      GjsMaybeOwned: Keep notification data only if DestroyNotify is needed
      dbus-wrapper: Remove interface skeleton flush idle on dispose
      dbus-wrapper: Use g_clear_handle_id everywhere
      gdbus-wrapper: Destroy the outstanding properties map on finalize
      testGObjectClass: Ensure objects have a toString definition
      GObject: Don't overwrite toString() method with one from Interface
      installed-tests: Disable eslint for tests using legacy Lang

Nauman Umer (1):
      Update README.md

Olivier Fourdan (2):
      build: Remove spurious closing bracket
      build: Add requirement on sysprof 3.33.2

Onur Şahin (1):
      Ensure const-correctness in C++ objects

Philip Chimento (185):
      build: Post-branch version bump
      context: Remove lazy flag from evaluated sources
      context: Fix gjs_context_eval() for non-zero-terminated strings
      gtype: Port weak pointer hash table to WeakCache
      value: Support marshalling custom fundamental types
      wrapperutils: Fix function name in comment
      wrapperutils: Factor out to_c_ptr() and transfer_to_gi_argument()
      wrapperutils: Use GIWrapperBase::typecheck() directly in calling code
      boxed: Move to C++-style API
      gerror: Move to C++-style API
      object: Move to C++-style API
      context: Use tracing for promise job queue
      object: Port object_init_list to GCVector
      arg: Factor interface case out of gjs_value_to_g_argument()
      function: Add more marshalling debug logs
      build: Move locale choosing into separate script
      build: Remove GETTEXT_PACKAGE variable
      build: Remove unused defines
      build: Build modules into libgjs
      tests: Don't output generated coverage data
      tests: Don't remove log handler during test
      arg: Remove unused argument
      wrapperutils: Remove unnecessary semicolon
      atoms: Remove unused argument
      context: Change EnvironmentPreparer to protected inheritance
      jsapi-util-args: Remove unused argument
      CI: Discard stdout of cpplint
      wrapperutils: Move TypecheckNoThrow type out of template
      boxed: Track ownership of boxed pointer better
      cairo: Take may_be_null into account in foreign struct conversion
      cairo: Don't free unowned Cairo structs
      console: Don't accept --profile after the script name
      build: Don't distribute generated GResource files
      release: Include NEWS from 1.56.1
      release: Prepare for 1.57.1
      build: Post-release version bump
      Gio: Add non-crashing overrides for Gio.Settings
      release: Copy NEWS from 1.56.2
      fundamental: Move to C++-style API
      cairo: Remove unused arguments to init functions
      arg: Remove unused argument
      boxed: Remove unused argument
      console: Remove unused arguments
      build: Introduce "used only in debug" annotations
      build: Annotate all unused arguments
      object: Rename field_setter_impl()
      gtype: Make finalize function a no-op
      union: Warn when passing arguments to constructor
      gdbus: Do some sanity checks in DBus skeleton
      build: Clean GSettings file
      context: Use Heap pointers for GC objects stored in vectors
      release: Prepare for 1.57.2
      build: Post-release version bump
      wrapperutils: Fix compiler warning on GCC 5.x
      CI: Update pinned fedora job
      wrapperutils: Move define_static_methods into GIWrapper
      interface: Move to C++-style API
      macros: Move GJS_ALWAYS_INLINE to macros.h
      maint: Rename variables named "string"
      module: Remove explicit comparison with nullptr
      maint: Remove C-style NULLs from some files
      maint: Remove GLib custom types from some files
      maint: Unify header guard style across all headers
      maint: Remove G_BEGIN_DECLS and G_END_DECLS from internal files
      util: Remove util/glib
      util: Move util/error to gjs/error-types
      maint: Fix header includes once and for all
      maint: Use C++ attributes where available
      js: Avoid unnecessary gjs_string_to_utf8()
      context: Destroy atoms before destroying context
      global: Lazy-define standard environment
      maint: Add cpplint exception
      maint: Remove cpplint exception from util/sp-capture-*
      maint: Fix cppcheck suppression comment
      importer: Remove usage of deprecated G_CONST_RETURN
      gdbus: Remove usage of depracted G_TYPE_INSTANCE_GET_PRIVATE
      GjsMaybeOwned: Clarify comment on heap allocation
      release: Prepare for 1.57.3
      build: Post-release version bump
      Change style guide doc to reflect current best practices
      release: Prepare for 1.57.4
      build: Post-release version bump
      CI: Force python2 when configuring JHBuild
      build: Recognize and prefer C.utf8 locale for tests
      build: Break output of `locale -a` into lines
      CI: Switch to Fedora for coverage-automatic job
      jsapi-util-root: Shorter way to get pointer to current context
      macros: Add annotation for GJS_JSAPI_RETURN_CONVENTION
      console: Make second GOptionEntry non-static
      arg: Prevent null pointer access in zero-length array case
      function: Free partially allocated cached function data
      testEverythingBasic: Fix outdated comment
      value: Take null boxed pointer into account when calling signal handler
      wrapperutils: Always set prototype private data
      tests: Add test for GLib.VariantDict.lookup failure case
      GLib: add GLib.Variant.recursiveUnpack()
      GLib: add alias for GLib.Variant.deepUnpack()
      release: Prepare for 1.57.90
      build: Post-release version bump
      heapgraph: Fix help for -e argument
      heapgraph: Improve WeakMap regex
      heapgraph: Add --hide-edge argument
      heapgraph: Add ability to label nodes
      heapgraph: Display both nodes of an interesting edge
      heapgraph: Clarify address in heap dump
      heapgraph: Allow selecting multiple targets
      heapgraph: Always keep "interesting" labels in graph
      heapgraph: Add root edges outside of search function
      heapgraph: Add an argument to print out unreachable nodes
      CI: Convert eslint JSON to YAML
      CI: Use new eslint syntax for globals
      js: Convert all tabs to spaces
      js: Run eslint --fix on all JS files
      js: Fix remaining eslint complaints
      CI: Add array-parens to eslint rules
      CI: Add block-scoped-var to eslint rules
      CI: Use camelcase
      CI: Add comma-dangle to eslint rules
      CI: Add curly to eslint rules
      CI: Add dot-location to eslint rules
      CI: Add eol-last to eslint rules
      CI: Add eqeqeq to eslint rules
      CI: Add func-call-spacing to eslint rules
      CI: Add func-style to eslint rules
      CI: Add lines-between-class-members to eslint rules
      CI: Add no-array-constructor to eslint rules
      CI: Add no-extra-bind to eslint rules
      CI: Add no-extra-parens to eslint rules
      CI: Add no-lonely-if to eslint rules
      CI: Add no-new-object to eslint rules
      CI: Disallow imports.mainloop in new code with no-restricted-properties
      CI: Add no-return-assign to eslint rules
      CI: Add no-shadow to eslint rules
      CI: Add no-throw-literal to eslint rules
      CI: Add no-trailing-spaces to eslint rules
      CI: Add extra patterns to no-unused-vars
      CI: Add no-useless-call to eslint rules
      CI: Add no-useless-constructor to eslint rules
      CI: Add object-shorthand to eslint rules
      CI: Add operator-linebreak to eslint rules
      CI: Add prefer-rest-params and prefer-spread to eslint rules
      CI: Add space-before-function-paren to eslint rules
      CI: Add space-in-parens and space-unary-ops to eslint rules
      CI: Add spaced-comment to eslint rules
      CI: Add valid-jsdoc to eslint rules
      CI: Add a bunch of minor rules to eslint that we already follow
      CI: Add a rule to prevent unnecessary _init() functions
      CI: Add a rule to prevent arrow functions in Jasmine test cases
      docs: Update Style_Guide.md
      CI: Add a rule to prevent accidentally switching off test cases
      tests: Reintroduce skipped tests that have been fixed
      tests: Update pending messages
      tests: Exclude generated resource files from code coverage
      tests: Move some tests around
      tests: Move bad overrides to 'badOverrides' directory
      tests: Fully implement gobject-introspection test suites
      tests: Move Cairo-based GIMarshallingTests test to testCairo
      release: Prepare for 1.57.91
      build: Post-release version bump
      object: Remove duplicate log message
      context: Add more logging around garbage collection
      build: Ignore __pycache__
      object: Remove duplicate reset of JS wrapper
      CI: Organize build jobs into recommended, minimal, and maximal
      CI: Add sysprof-devel to Fedora images
      CI: Remove Ubuntu LTS job
      CI: Drop xvfb-run server-args
      CI: Don't try to connect to accessibility bus in examples tests
      CI: Fix WebKit example
      profiler: Mark unused function parameters
      build: Remove xvfb-tests option
      maint: Fix file permission
      tests: Override fatal-warnings/fatal-criticals on particular tests
      fundamental: Deal with missing introspection info
      Gtk: Provide better message when forgetting a template signal handler
      tests: Expect GTK_IS_WINDOW assertion failure in destroyed window test
      build: Remove regularly scheduled CI jobs
      build: Add glib-2.0 and gio-2.0 to public pkg-config requirements
      CI: Install meson in Docker images
      CI: Update pinned job
      CI: Move build_minimal job to Fedora
      CI: re-enable profiler
      release: Prepare for 1.57.92
      build: Post-release version bump
      release: Prepare for 1.58.0

Sonny Piers (2):
      add override GLib.VariantDict.lookup
      Remove usage of Lang in non-legacy code

Stephane Seng (2):
      arg: Fix the marshalling of GPtrArrays by ensuring that their elements are considered as pointers instead of structures
      CI: Fix Docker images build

Stéphane Seng (2):
      tests: Add a regression test case for GPtrArrays and GArrays of structures
      tests: Enable regression test cases for GPtrArrays and GArrays of structures

namnumr (4):
      bug fix: ignore comment and eval commands
      added summary for debug commands
      added helpText for debugger commands
      debugger: Fix eslint errors

Version 1.58.0
--------------

- No change from 1.57.92.

Version 1.57.92
---------------

- Closed bugs and merge requests:
  * tests: Enable regression test cases for GPtrArrays and GArrays of structures
    [Stéphane Seng, !334]
  * Various maintenance [Philip Chimento, !333, !335]

Version 1.57.91
---------------

(NEWS truncated at 15 lines)