gjs: Autospec creation for update from version 1.82.1 to version 1.84.1
Bartłomiej Piotrowski (1):
      ci: Switch to GNOME GitLab mirror of ci-templates

Evan Welsh (1):
      module loader: Wrap GI loadAsync in Promise

Gary Li (17):
      global: add source map registry slots
      modules/internal: bring in mozilla source-map library
      global: implement atob support
      modules: add source map support
      debugger: add source map support
      context: add source map support for non-module files
      installed-tests: add tests for module and non-module debugger runs
      tests: add tests for source maps in exceptions logging
      console: persist REPL history to user defined path
      gobject: handle gjs_context_dispose unroots wrappers but ObjectInstance still exists
      closure: guard against non-js thread when marshalling
      debugger: show private fields in print and keys command
      profiler: only build dynamic string for profiler label if profiling
      prettyPrinter: handle null prototype and nullish toString
      overrides: add simpler GObject.Value constructor API
      testRegress: add corresponding GJS tests for discontinuous flag values with private values
      testWarnings: run gc wrapper test only under Gtk4

Jan Tojnar (3):
      tests: Prevent `gjs:dbus / Gtk4` connecting to accessibility bus
      tests: Make `gjs:Scripts / Warnings` conditional on GTK 4 being available
      tests: Make `gjs:Scripts / Warnings` conditional on DISPLAY

Jordan Petridis (2):
      release: Prepare for 1.83.2
      build: Post-release version bump

Marco Trevisan (Treviño) (31):
      package: Try to load resource module name if available
      package: Use String.replaceAll instead of Regex
      gjs: Add simple class to wrap a C++ object inside a JS Object
      js-value-inl: Add implementation for js value to c-string
      arg/arg-cache: Do not duplicate strings that we can steal instead
      object: Bind GIFieldInfo to each field property
      object: Use simpler property accessors if properties are not actionable
      value: Use direct access to GValue field elements
      object: Generate properties setters and getters per type
      object/value: Warn when getting properties that can't be stored in JS numbers
      object: Avoid trying to resolve any field if it's already defined
      object: Reuse the same property descriptors (and associated objects)
      deprecation: Handle null pointers location strings nicely
      object: Add support for using property setters and getters
      object: Remember the getters/setters function pointer to call
      object: Use properties setters and getters with generated functions
      arg-cache: Store less information for return type info
      arg-cache: Add simple BasicType return argument and use to return basic types
      arg-cache: Add in argument support for Error type
      arg-cache: Add in and out Arguments for G(S)Lists
      arg-cache: Add marshaller for simple GHash types
      arg-cache: Add marshallers for C arrays of basic types
      arg-cache: Add marshaller classes for ByteArray
      arg-cache: Add marshallers for GArrays and GPtrArrays containing simple types
      arg-cache: Add arguments for G(S)List and GHash out parameters
      arg-cache: Add basic arrays out arguments
      arg-cache: Use a templated structure to generate arguments for containers
      arg-cache: Add arguments marshallers for inout basic types
      arg-cache: Add inout arguments for basic type containers
      object: Add tests for static virtual functions
      object: Add support for static virtual functions

Philip Chimento (114):
      build: Post-release version bump
      build: Post-branch version bump
      maint: Fix gobject-introspection-tests submodule path
      arg: Un-templateize gjs_arg_unset()
      gerror: Fix incorrect comment
      js: Move auto pointers to their own headers
      js: Introduce GErrorResult type
      js: Fix IWYU includes
      build: Require g-i 1.72
      misc: Remove _gjs_memdup2()
      docs: Remove dead links, apps no longer using GJS, and archived apps
      docs: Shorten list of apps to just GNOME Core and Circle
      docs: Alphabetize list of apps
      GLib: Make GLib.log_set_writer_default work properly
      arg-cache: NotIntrospectable should not assume GITypeInfo is available
      arg-cache: Label instance parameters as such
      arg-cache: Replace tuple with convenience struct
      arg-cache: Remove parameter pack expansion in ArgsCache
      arg-cache: Move CallerAllocates parameter to constructor
      arg-cache: Move Callback parameters to constructor
      arg-cache: Move Array parameters to constructor
      arg-cache: Remove return values of set_argument() and friends
      arg-cache: Move GITypeInfo out of common initialization args
      arg-cache: Templatize the GITypeInfo in build_interface_in_arg()
      auto: Add function to safely move JS::UniqueChars to Gjs::AutoChar
      value: Avoid ambiguity on 32-bit in gvalue_to_string()
      maint: Update to latest gobject-introspection-tests
      tests: Fix typo
      tests: Test for current behaviour of skipped parameters
      tests: Write tests for all the new stuff added to g-i-tests
      boxed: Fix memory leak when attempting to write unsupported field
      tests: Skip dev_t inout for the time being
      CI: Fix cppcheck job
      CI: Update to use GNOME Release Service
      maint: Adapt maintainer-upload-release script for GNOME Release Service
      maint: Add more stable branches to maintainer-tag-release
      tests: Suppress cppcheck error
      deprecation: Accept std::string for deprecation message format arguments
      arg-cache: Untemplatize ArgsCache::set_array_argument
      arg-cache: Use Maybe for return types
      arg-cache: Use Maybe for instance types
      js-value-inl: Don't consider float/integral types comparable
      arg-cache: Remove default GITypeTag for NumericReturn
      arg-cache: Use full tagged types in Numeric arg-cache
      gi: Use format_name() in exception and debug messages
      tools: More concise invocation of which
      arg: Reorganize arg.cpp file into "to", "from", and "release" sections
      arg: Remove unnecessary const reference
      arg-cache: Remove unnecessary ReturnValue alias
      arg: Avoid converting GHashTable key to UTF-8 and back
      arg-cache: Check for GdkAtom first
      CI: Remove debug topic logs from build_recommended
      arg-cache: Move zero-terminated & fixed-size arrays into build_normal_in(out)_arg()
      arg-cache: Rewrite FallbackInterfaceIn to only use saved introspection info
      arg: Split basic types out of gjs_value_from_g_argument()
      arg: Split GError out of gjs_value_to_gi_argument()
      arg: Split out functions for marshalling G(S)Lists with basic types
      arg: Split GHashTables with basic key & value types out of gjs_value_from_gi_argument
      arg: Split basic array marshalling out of array marshalling
      arg-cache: Remove generic marshallers
      arg-cache: Adjust GenericInOut release semantics
      arg-cache: Add marshaller for GdkAtoms
      arg-cache: Make ExplicitArray a basic extendable type
      arg-cache: Add support for Basic types out specific arguments
      release: Prepare for 1.83.1
      build: Post-release version bump
      format: Fix %Id to work regardless of libc implementation
      object: Fix missing static_type_name template parameter
      object: Fix relaxed vs strict conversion in property setter via paramspec
      console: Use readline callback-based API
      object: Handle simple getters/setters with type void*
      object: Pass GIFunctionInfo to property callers by pointer
      object: Factor out create_getter_invoker and create_setter_invoker
      object: Use g_callable_info_load_arg before create_setter_invoker
      object: Handle mismatch in type of property with type of C accessor
      build: Use Meson 1.4 and full_path() feature
      Revert "object: Fix relaxed vs strict conversion in property setter via paramspec"
      value: Avoid more ambiguity on 32-bit in gvalue_to_string()
      value: Specify signed char in gvalue_get specialization
      function: Remove inferrable template type parameter
      arg-types-inl: Replace static_type_name() with MarshallingInfo struct
      arg-types-inl: Replace <T, TAG> pairs with a single TAG
      arg-types-inl: Explain JSValueHolder::Strict and Relaxed
      object: Handle signed and unsigned long properties in fast path
      js-value-inl: Work around case where int64_t is long long
      util: Fix memory leak when newlocale fails
      Update g-i-tests
      release: Prepare for 1.83.3
      build: Post-release version bump
      release: Prepare for 1.83.4
      build: Post-release version bump
      module loader: Move jsdoc types to environment file, and correct jsdoc
      module loader: Fix nullish type confusion
      source maps: Use resolveRelativePath directly instead of resolveSpecifier
      module loader: Fix crash when dynamic importing unknown URI scheme
      module loader: Never return null from loadURI()
      module loader: Fix crash on dynamically importing a module with sourcemap
      tools: Update package lockfile
      tools: Add typecheck script
      module loader: Add missing types for module hooks
      CI: Add typecheck job
      build: Shorten debugger test names
      arg-cache: Pack Argument::Init struct
      CI: Remove mozjs115 jobs
      build: Remove git-evtag from maintainer-tag-release script
      CI: Remove include_what_you_use messages from cpplint
      value: Fix typo in error message
      value: Choose correct template specialization for enum/flags
      arg: Remove unnecessary constref to JS::HandleValue
      internal: Fix name of function
      release: Prepare for 1.83.90
      release: Prepare for 1.84.0
      CI: Temporarily skip building container
      release: Prepare for 1.84.1

Ray Strode (1):
      gjs-util: make gjs_setlocale thread-safe

Sebastian Wiesner (1):
      Fix return value of load_contents_async

- 1.84.0 was never released due to Freedesktop outage. 1.84.1 is
  identical.

Version 1.84.0
--------------

- Closed bugs and merge requests:
  * tests: Prevent failures when GTK4/DISPLAY is missing [!986, Jan Tojnar]
  * testWarnings: run gc wrapper test only under Gtk4 [!987, Gary Li]

Version 1.83.90
---------------

- Closed bugs and merge requests:
  * Various maintenance [!982, Philip Chimento]

(NEWS truncated at 15 lines)